import "./styles/radix-theme.css";
import "./styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import { Container, Theme, ThemePanel } from "@radix-ui/themes";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme accentColor="green" grayColor="sand" radius="none">
          <NavBar />
          <main className="max-w-4xl m-auto mt-4 px-4">
            <Container>{children}</Container>
          </main>
          <ThemePanel defaultOpen={false} />
        </Theme>
      </body>
    </html>
  );
}
